apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-netpol
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-data
    ports:
    - protocol: TCP
      port: 27017
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: openshift-dns
    ports:
    - protocol: UDP
      port: 53
